### PR TITLE
Update RegEx to properly find SAT value and resolve #52.

### LINKED ISSUE #52: Arm Home, Away, and Disarm no longer function
The Arm Home, Away, and Disarm functions no longer work on the Alarm Control Panel, however the Sensor Status still works.   

Receiving the following dump in the logs:  "You do not have access to the requested feature"
and at the end of the dump - 
**5/23/2022, 4:54:37 PM Pulse setAlarmState Success. Forced?:undefined**

     <td class="p_whiteBoxTopRight"></td>

    </tr>

    <tr>

        <td class="p_whiteBoxMiddleLeft"></td>

        <td class="p_whiteBoxMiddleCenter" align="center">

                    <div class="p_headerShim2">
                        <div class="p_signinLogoStyle">
                            
                            <a href="http://www.adt.com" target="_blank">
                                <div class="p_customLogo"></div>
                            </a>
                        </div>
                    </div>
                    <br/>
<br/>
    **<div id="errorDivMessage">
        <br/>
<div style="text-align:center">You do not have access to the requested feature.</div>
        <br/><br/><br/>**
        <div id="closebtn" style="display:none;"><input type="button" id="close" name="close" value="Close" alt="Close" class="p_btn p_btnXnormal" onclick="javascript:window.close()" onmouseover="javascript:btnHover(this,'X')" onmouseout="javascript:btnNormal(this,'X')" onmousedown="javascript:btnDown(this,'X')" onmouseup="javascript:btnNormal(this,'X')"  data-fitLabel="shrink"/><style type="text/css">#testSizeclose {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizeclose" class="p_btn p_btnXnormal" >Close</div></div>
        <div id="fullwindow"><input type="button" id="gotoportal" name="gotoportal" value="Return to Portal" alt="Return to Portal" class="p_btn p_btnXnormal" onclick="javascript:goToUrl('/myhome/23.0.0-99/summary/summary.jsp')" onmouseover="javascript:btnHover(this,'X')" onmouseout="javascript:btnNormal(this,'X')" onmousedown="javascript:btnDown(this,'X')" onmouseup="javascript:btnNormal(this,'X')"  data-fitLabel="shrink"/><style type="text/css">#testSizegotoportal {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizegotoportal" class="p_btn p_btnXnormal" >Return to Portal</div>&nbsp;&nbsp;
                         <input type="button" id="gotosignin" name="gotosignin" value="Go to Sign In" alt="Go to Sign In" class="p_btn p_btnXnormal" onclick="javascript:goToUrl('/myhome/23.0.0-99/access/signin.jsp')" onmouseover="javascript:btnHover(this,'X')" onmouseout="javascript:btnNormal(this,'X')" onmousedown="javascript:btnDown(this,'X')" onmouseup="javascript:btnNormal(this,'X')"  data-fitLabel="shrink"/><style type="text/css">#testSizegotosignin {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizegotosignin" class="p_btn p_btnXnormal" >Go to Sign In</div>
        </div>
        <br><br>
    </div>
    <script type="text/javascript">
        var errorWindow = getPortalScreenDimensions();
        if  (errorWindow.w < 700 || errorWindow.h < 500)
        {
            window.resizeTo( 700, 500 );
        }
        window.setTimeout(()=> {
        	const actionBtn = document.getElementById('gotosignin') || document.getElementById('gotoportal');
	        actionBtn?.focus();
        }, 0);
    </script>
                    

        </td>

        <td class="p_whiteBoxMiddleRight"></td>

    </tr>

    <tr>

        <td class="p_whiteBoxBotLeft"></td>

        <td class="p_whiteBoxBotCenter"></td>

        <td class="p_whiteBoxBotRight"></td>

    </tr>

</table>

                    
                    <div style="width:620px;height:1px;"></div>
                    
                    

         </td>

         <td class='p_raisedBoxMiddleRight'></td>

     </tr>

     <tr>

         <td class='p_raisedBoxFooterLeft'></td>

         <td class='p_raisedBoxFooterCenter' width="100%"></td>

         <td class='p_raisedBoxFooterRight'></td>

     </tr>                   

     <tr>

         <td class='p_raisedBoxBottomLeft'></td>

         <td class='p_raisedBoxBottomCenter'></td>

         <td class='p_raisedBoxBottomRight'></td>

     </tr>

</table>

                    </td>
                </tr>
                <tr height=5><td colspan=2></td></tr>
            </table>
            <span class="p_smallCommentText"><a class="p_footerLink" href="http://www.adt.com" target="_blank">ADT Security Services</a>
                <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/about-adt/legal/privacy-policy" target="_blank">Privacy Policy</a>
                <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/about-adt/legal/adt-pulse-terms-of-use" target="_blank">ADT Pulse Terms of Use</a>
                <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/help" target="_blank">Customer Support</a>
                </span>
            <br /><br />
        </div>
        
        </body>
    </html>
::
**5/23/2022, 4:54:37 PM Pulse setAlarmState Success. Forced?:undefined**

### PR DESCRIPTION
**Pull request by d0nni3q84**

### CODE REVIEW

**Review by digitalcraig — APPROVED** [review]

**Comment by d0nni3q84** [comment]
> Do I understand correctly that the sat value is now always required?

Correct. In my testing, all of the sensors are closed and `sat` is part of the query string sent to the **quickcontrol/armDisarm.jsp** URI when examining the input buttons. The second commit on this PR addresses this and we could simplify the code further, but wanted to start with minimal changes.

> Also, did something change in the html returned that would require updates to our tests? Or was this only server side change?

I think the RegEx used was not anticipating order change in the query string. So searching for `UUID` following `sat` addresses this. NOTE: There is another UUID in the HTML for **summary/changeMode.jsp** URI, so it would not be sufficient to match on `UUID` alone.

---

`Arm Away` is **security_button_0** with

```
onclick="setArmState('quickcontrol/armDisarm.jsp','Arming Away','0','2','false','href=rest/adt/ui/client/security/setArmState&armstate=disarmed&arm=away&sat=11111111-2222-3333-4444-555555555555')"
```

`Arm Stay` is **security_button_1** with

```
onclick="setArmState('quickcontrol/armDisarm.jsp','Arming Stay','1','2','false','href=rest/adt/ui/client/security/setArmState&armstate=disarmed&arm=stay&sat=11111111-2222-3333-4444-555555555555')"
```

**Comment by digitalcraig** [comment]
> Correct. In my testing, all of the sensors are closed and `sat` is part of the query string sent to the **quickcontrol/armDisarm.jsp** URI when examining the input buttons. The second commit on this PR addresses this and we could simplify the code further, but wanted to start with minimal changes.

Based on that, I'm thinking the statement setting sat needs to be moved out of the if statement:

```javascript
if (action.newstate!="disarm" && action.isForced!=true && body.includes("Some sensors are open or reporting motion"))
```

The disarm test is failing:

```
  ADT Pulse Disarm Test
5/24/2022, 1:41:58 PM Pulse.setAlarmState Setting Alarm Status
5/24/2022, 1:41:58 PM Pulse.setAlarmState calling the url :https://portal.adtpulse.com/myhome/13.0.0-153/quickcontrol/armDisarm.jsp?href=rest/adt/ui/client/security/setArmState&armstate=stay&arm=off&sat=
5/24/2022, 1:41:58 PM Pulse setAlarmState Failed with: undefined
    1) Should disarmed alarm

  ADT Pulse Arm Stay Test
5/24/2022, 1:41:58 PM Pulse.setAlarmState Setting Alarm Status
5/24/2022, 1:41:58 PM Pulse.setAlarmState calling the url :https://portal.adtpulse.com/myhome/13.0.0-153/quickcontrol/armDisarm.jsp?href=rest/adt/ui/client/security/setArmState&armstate=disarmed&arm=stay&sat=
5/24/2022, 1:41:58 PM Pulse setAlarmState Failed with: undefined
    2) Should arm the alarm to stay

  ADT Pulse Arm Away Test without forcing
5/24/2022, 1:41:58 PM Pulse.setAlarmState Setting Alarm Status
5/24/2022, 1:41:58 PM Pulse.setAlarmState calling the url :https://portal.adtpulse.com/myhome/13.0.0-153/quickcontrol/armDisarm.jsp?href=rest/adt/ui/client/security/setArmState&armstate=disarmed&arm=away&sat=
5/24/2022, 1:41:58 PM Pulse setAlarmState Failed with: undefined
    3) Should arm the alarm to stay

  ADT Pulse Forced Arm Away Test
5/24/2022, 1:41:58 PM Pulse.setAlarmState Setting Alarm Status
5/24/2022, 1:41:58 PM Pulse.setAlarmState calling the url :https://portal.adtpulse.com/myhome/13.0.0-153/quickcontrol/armDisarm.jsp?href=rest/adt/ui/client/security/setArmState&armstate=disarmed&arm=away&sat=
5/24/2022, 1:41:58 PM Pulse setAlarmState Failed with: undefined
    4) Should arm the alarm to stay
```

**Comment by d0nni3q84** [comment]
Updated `zonestatus.jsp` to match the content on https://portal.adtpulse.com/myhome/23.0.0-99/summary/summary.jsp. Test should pass if I didn't mess anything else up :).

**Comment by digitalcraig** [comment]
The arm/disarm tests are still failing because sat is undefined. The code to set sat is not run unless the new state is not disarming and the body of the response includes the string "Some sensors are open or reporting motion" (see earlier comment regarding if statement). If the expectation is that sat is always used, then it should be set regardless of the state and status of the sensors.

The update test also now fails because the new zonestatus.jsp has 11 devices and the test expects 7 as well as specific zones. Either the test should be updated or the devices in the new zonestatus.jsp updated to match.

Here's the test as written:

```
    expect(zones).has.a.lengthOf(7);
    expect(zones[0].id).contains("sensor");
    expect(zones[0].name).equals("BACK DOOR");
    expect(zones[0].state).equals("devStatOK");
```

**Pull request closed without merging**
